# Defaults for all profiles.
[profile.default]
src = "src"                                                      # Set the source directory.
test = "test"                                                    # Set the test directory.
out = "out"                                                      # Set the output directory for the artifacts.
libs = ["lib"]                                                   # Configure an array of library directories.
cache = true                                                     # Enable caching.
cache_path = "cache"                                             # Set the path to the cache.
force = false                                                    # Do not ignore the cache.
solc_version = "0.8.20"                                          # Set the Solidity compiler version.
evm_version = "shanghai"                                         # Set the EVM target version.
optimizer = true                                                 # Enable the Solidity compiler optimiser.
optimizer_runs = 200                                             # Configure the number of optimiser runs.
via_ir = false                                                   # Prevent the compilation pipeline from running through the Yul intermediate representation.
vyper = { optimize = "gas" }                                     # Configure the Vyper compiler optimisation mode.
verbosity = 3                                                    # Set the verbosity level for the tests.
ffi = true                                                       # Enable the foreign function interface (ffi) cheatcode.
fuzz = { runs = 256, max_test_rejects = 65_536 }                 # Configure the number of fuzz runs and maximum number of combined inputs that may be rejected for the tests.

# Default overrides for the CI runs.
[profile.ci]
force = true                                                     # Perform always a clean build.
verbosity = 4                                                    # Increase the verbosity level for the tests.
fuzz = { runs = 10_000, max_test_rejects = 350_000 }             # Increase the number of fuzz runs and maximum number of combined inputs that may be rejected for the tests.